development:
  adapter: postgresql
  encoding: unicode
  database: coyote-development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: coyote-test
  pool: 5
  host: localhost
